config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "in#hi"
  get "morehi", to: "in#morehi"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/rand_number.rb
class RandNumber < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/in_controller.rb
class InController < ApplicationController
    def hi
        rand = Random.rand(1..10)
        RandNumber.create(number: rand)
        @r = rand.to_s
        @lastnumbers = RandNumber.all.limit(5).order("created_at DESC")
    end
    def morehi
      @morenumbers = RandNumber.all.offset(5).order("created_at DESC")
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/in_helper.rb
module InHelper
end

app/views/in/hi.erb
<h1>hi, rails!</h1>
<p>случайное число от 1 до 10: <%= @r%> </p>
<h1>Последние случайные числа</h1>
<ol>
  <% @lastnumbers.each do |ln| %>
    <li> Число <%= ln.number.to_s + ' угадано ' + ln.created_at.to_s %> </li>
  <% end %>
</ol>
<p><b> <%=link_to "Другие результаты", morehi_path%> </b></p>

app/views/in/morehi.erb
<h1>Другие случайные числа</h1>
<ol>
  <% @morenumbers.each do |ln| %>
    <li> Число <%= ln.number.to_s + ' угадано ' + ln.created_at.to_s %> </li>
  <% end %>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>